[tool.poetry]
name = "organizer"
version = "0.1.0"
description = ""
authors = ["rolando <castillor493@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
typer = "^0.20.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
